# Model arguments
model_name_or_path: llava-hf/llama3-llava-next-8b-hf
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: ccvl/3DSRBench
data_dir: /home/ychou11/LMUData/images/3DSRBench/
dataset_configs:
- all
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 7

# GRPO trainer config
bf16: true
use_vllm: false
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
num_generations: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: llava-hf/llama3-llava-next-8b-hf-Open-R1-GRPO
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_completion_length: 1024
max_steps: -1
num_train_epochs: 1
output_dir: data/llama3-llava-next-8b-hf-Open-R1-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 4   
per_device_train_batch_size: 1
push_to_hub: false
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
